language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - git submodule update --init --recursive

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install build-essential libxdg-basedir-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get -qq --allow-unauthenticated install gcc-4.9 g++-4.9; export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get -qq --allow-unauthenticated install clang-3.6; export CXX="clang++-3.6" CC="clang-3.6"; fi
  - wget http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
  - tar xf lcov-1.11.tar.gz
  - cd lcov-1.11 && sudo make install
  - cd ..
  - gem install coveralls-lcov

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON -DCOVERAGE=ON -DGCOV_PATH=/usr/bin/gcov-4.9 .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
  - lcov -v
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$CXX" = "g++-4.9" ]; then make utils_coverage && coveralls-lcov --repo-token X6q6ZWshmjbZ8jKMVfwkeDdbA1v8vd7UX coverage.info; fi