language: cpp

os:
  - linux
  - osx

before_install:
  - git submodule update --init --recursive

env:
  - CXX=clang-3.6 CONFIG=Debug
  - CXX=clang-3.6 CONFIG=Release
  - CXX=g++-4.9 CONFIG=Debug
  - CXX=g++-4.9 CONFIG=Release

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq

install:
  - sudo apt-get -qq install build-essential
  - sudo apt-get -qq --allow-unauthenticated install clang-3.6 gcc-4.9 g++-4.9

script:
  - cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=$CONFIG -DSTANDALONE=ON .
  - make -j4
  - make -j4 check
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
