dist: trusty
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=5.0 LLVM_VERSION=5.0.1 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=5.0 LLVM_VERSION=5.0.1 BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Release
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - libxdg-basedir-dev
    #         - lcov
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Debug
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - libxdg-basedir-dev
    #         - lcov
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=7 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxdg-basedir-dev
            - lcov
      env:
        - COMPILER=7 BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Debug
      osx_image: xcode9
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode9

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}/local
  - cd ${DEPS_DIR}
  - export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
  - export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
  - export LDFLAGS="-L${DEPS_DIR}/local/lib"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  ############################################################################
  # Install clang on linux
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "clang++" ]]; then
      if [[ "$COMPILER" == "4.0" ]]; then
        travis_retry wget --quiet -O - http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local
      else
        travis_retry wget --quiet -O - http://releases.llvm.org/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local
      fi


      export PATH=${DEPS_DIR}/local/bin:${PATH}
      export LDFLAGS="${LDFLAGS} -lc++ -lc++abi -lm"
      export CXXFLAGS="${CXXFLAGS} -isystem ${DEPS_DIR}/local/include/c++/v1 -stdlib=libc++"
      export CXX="clang-${COMPILER}" CC="clang-${COMPILER}"
      ${CXX} -v
    fi

  - |
    git clone --single-branch https://github.com/fmtlib/fmt.git --branch 4.0.0
    cd fmt
    cmake -DFMT_DOC=OFF -DFMT_TEST=OFF -DFMT_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/local
    make install

  - if [ "$CXX" = "g++" ]; then export CXX="g++-${COMPILER}" CC="gcc-${COMPILER}"; fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      gem install coveralls-lcov
    fi
  - cd ${TRAVIS_BUILD_DIR}

script:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux"] && ["${CXX}" != "clang++" ]; then
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON -DCOVERAGE=ON -DGCOV_PATH=/usr/bin/gcov-6 -DCMAKE_PREFIX_PATH=${DEPS_DIR}/local .
    else
      cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON -DCMAKE_PREFIX_PATH=${DEPS_DIR}/local .
    fi
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
  - lcov -v
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$CXX" = "g++-6" ]; then make utils_coverage && coveralls-lcov --repo-token X6q6ZWshmjbZ8jKMVfwkeDdbA1v8vd7UX coverage.info; fi

after_failure:
  - cat Testing/Temporary/LastTest.log
