language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

before_install:
  - git submodule update --init --recursive

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
