language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test

    packages:
        - cmake
        - build-essential
        - libxdg-basedir-dev
        - gcc-4.9
        - g++-4.9
        - clang-3.7
        - lcov

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - gem install coveralls-lcov
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON -DCOVERAGE=ON -DGCOV_PATH=/usr/bin/gcov-4.9 .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
  - lcov -v
  - if [ "$BUILD_TYPE" = "Debug" ] && [ "$CXX" = "g++-4.9" ]; then make utils_coverage && coveralls-lcov --repo-token X6q6ZWshmjbZ8jKMVfwkeDdbA1v8vd7UX coverage.info; fi

deploy:
  provider: biicode
  user: dirkvdb
  password:
    secure: HBkRdnG+sL8r8ZvSdqFMYQ0nG8hDia8KDZb+fPaWFh9B/Pz0bptbcn+jilmgkf9EzlGocF+QqJ6SPFmUbzEb8yrdn0vzWsvMf8Hy4kLyPIDyQz+MCv02EY9npwVVJ9XXcP50lawZ1Bgnrd50vDJCTMMLCiF5O4y0yHex83WkLJI=
  on: biicode
