dist: trusty
language: cpp
group: travis_latest

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - libxdg-basedir-dev
      env:
        - COMPILER=5.0 LLVM_VERSION=5.0.1 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
      env:
        - COMPILER=5.0 LLVM_VERSION=5.0.1 BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libxdg-basedir-dev
      env:
        - COMPILER=4.0 LLVM_VERSION=4.0.0 BUILD_TYPE=Release
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - libxdg-basedir-dev
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Debug
    # - compiler: gcc
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-6
    #         - libxdg-basedir-dev
    #   env:
    #     - COMPILER=6 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxdg-basedir-dev
      env:
        - COMPILER=7 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libxdg-basedir-dev
      env:
        - COMPILER=7 BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Debug
      osx_image: xcode9
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode9

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}/local
  - cd ${DEPS_DIR}
  - export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
  - export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
  - export LDFLAGS="-L${DEPS_DIR}/local/lib"

  ############################################################################
  # Install clang on linux
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "clang++" ]]; then
      if [[ "$COMPILER" == "4.0" ]]; then
        travis_retry wget --quiet -O - http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local
        export PATH=${DEPS_DIR}/local/bin:${PATH}
        export CXXFLAGS="${CXXFLAGS} -isystem ${DEPS_DIR}/local/include/c++/v1 -stdlib=libc++"
      else
        travis_retry wget --quiet -O - http://releases.llvm.org/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local
        export CXXFLAGS="${CXXFLAGS} -stdlib=libc++"
      fi

      export CXX="clang++" CC="clang"
      ${CXX} -v
    fi

  - |
    git clone --single-branch https://github.com/fmtlib/fmt.git --branch 4.0.0
    cd fmt
    cmake -DFMT_DOC=OFF -DFMT_TEST=OFF -DFMT_INSTALL=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS_DIR}/local
    make install

  - if [ "$CXX" = "g++" ]; then export CXX="g++-${COMPILER}" CC="gcc-${COMPILER}"; fi

install:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON -DCMAKE_PREFIX_PATH=${DEPS_DIR}/local .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
